#! /bin/sh
# Copyright (c) 2009, 2011 Richard Kettlewell.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
set -e

add_p4_user() {
  echo "Creating p4d user and group"
  adduser --quiet --system --group --shell /bin/sh --home /var/lib/p4 \
    --no-create-home p4d
}

case "$1" in
configure )
  if grep -q ^p4d: /etc/passwd; then
    :
  else
    add_p4_user
  fi
  if test ! -d /var/lib/p4; then
    echo "Creating /var/lib/p4"
    mkdir -m 700 /var/lib/p4
    chown p4d:p4d /var/lib/p4
  fi
  update-rc.d p4 defaults 92 19 > /dev/null
  invoke-rc.d p4 restart
  ;;
abort-upgrade )
  invoke-rc.d p4 restart
  ;;
reconfigure )
  invoke-rc.d p4 restart
  ;;
esac
